Feature/home beta
vivitek/god-view pull request #6
Opened 2021-05-11 09:28 UTC by Dythic

2021-05-11 11:10 UTC, matfire requested changes

2021-05-11 11:10 UTC, matfire commented on src/pages/stats/Stat.js
> +    fetch("http://dashboard.docker.localhost/api/http/routers")
removed commented code if not used

2021-05-11 11:10 UTC, matfire commented on src/pages/stats/Stat.js
> +          <Table className={classes.table} aria-label="simple table">
wrong aria-label

2021-05-11 11:10 UTC, matfire commented on src/pages/home/Home.js
> +        <Accordion>
should be a separate component: avoid repetition and multiple sources of errors

2021-05-11 11:10 UTC, matfire commented on src/pages/home/Home.js
> +  const [serv, setServ] = useState(null);
avoid useState(null) and use proper error handling

2021-05-11 11:10 UTC, matfire commented on src/pages/home/Home.js
> +    fetch("https://dashboard.vincipit.com/")
setup catch strategy instead of ignoring error thrown

2021-05-11 11:10 UTC, matfire commented on src/pages/home/Home.js
> +              <img alt="travis" src={"https://api.travis-ci.com/vivitek/backend.svg?branch=master"}/>
alt should be meaningful, not just a repetition for each accordion

2021-05-11 11:11 UTC, matfire requested changes

2021-05-11 11:11 UTC, matfire commented on build/asset-manifest.json
> +{
remove build files: they should not be pushed

2021-05-11 11:48 UTC, thmarinho commented on src/pages/home/Home.js
> +    fetch("https://api.server.vincipit.com/")
use axios instead

2021-05-11 11:48 UTC, thmarinho commented on src/pages/home/Home.js
> +    fetch("https://api.xana.vincipit.com/")
same

2021-05-11 11:48 UTC, thmarinho commented on src/pages/home/Home.js
> +                <div className="cercleG"></div>
GreenCircle

2021-05-11 11:48 UTC, thmarinho commented on src/pages/home/Home.js
> +                <div className="cercleR"></div>
RedCircle

2021-05-11 15:06 UTC, matfire requested changes

2021-05-11 15:06 UTC, matfire commented on src/pages/home/Home.js
> +                <img alt="travis" src={row.Travis}/>
alt tags still not valid

2021-05-11 15:06 UTC, matfire commented on src/pages/home/Home.js
> +          <Accordion>
Accordion should be in separate component for clarity

2021-05-11 15:06 UTC, matfire commented on src/pages/home/Home.js
> +    <div className="homePage">
use coherent style: makeStyle or custom styles, pick one

2021-05-13 14:41 UTC, thmarinho requested changes
remove DataTable.* files, they are empty

2021-05-13 14:41 UTC, thmarinho commented on src/pages/home/Home.js
> +  return {Service, Title, CodeCov, Travis};
should not be in uppercase

2021-05-13 14:41 UTC, thmarinho commented on src/pages/home/Home.js
> +  createData(1, 'Serveur', 'https://codecov.io/gh/vivitek/backend/branch/master/graph/badge.svg', 'https://api.travis-ci.com/vivitek/backend.svg?branch=master'),
do not use a function, create your objects as a grown man

2021-05-13 14:41 UTC, thmarinho commented on src/pages/stats/Stat.js
> +  createData('ok', 'PathPrefix(/api)', 'traefik', 'api@internal', 'api@internal', 'Internal'),
same

2021-05-13 14:41 UTC, thmarinho commented on src/pages/stats/Stat.js
> +  return {Status, Rule, Entrypoints, Name, Service, Provider};
same

2021-05-13 14:41 UTC, thmarinho commented on src/pages/stats/Stat.js
> +  createData('ok', 'Host(`dashboard.server.vincipit.com`)', 'secureweb', 'traefik@docker', 'api@internal', 'Docker'),
why are all statuses hard coded ?

2021-05-13 14:41 UTC, thmarinho commented on src/pages/home/Home.js
> +          <Accordion>
missing key prop

2021-05-13 14:41 UTC, thmarinho commented on src/pages/stats/Stat.js
> +                <TableRow key={row.name}>
{rows.map((row, idx) => (
  <TableRow key={idx}>
  [...]

2021-05-13 14:41 UTC, thmarinho commented on src/pages/stats/Stat.js
> +    <div className="homePage">
this is not the home page, should change class name

2021-05-13 14:41 UTC, thmarinho commented on src/pages/home/Home.js
> +import ExpandMoreIcon from '@material-ui/icons/ExpandMore';
import { Accordion, AccordionSummary, AccordionDetails, Typography } from "@material-ui/core"

2021-05-13 14:41 UTC, thmarinho commented on src/pages/stats/Stat.js
> +import TableContainer from '@material-ui/core/TableContainer';
same

2021-07-17 14:28 UTC, closed without merging